### ISSUE TITLE
Keep track of money forgotten by insurance company and then collected 

### ISSUE THREAD

**Issue by mitchbaum** [mitchbaum/RoofTracker-Web-App#10]
The entire value of RT relies on collecting lost insurance money the adjuster claims he/she sent, but our records indicate there should be more money owed to the HO. Before RT, this money would not be collected because the information was too convoluted and time-consuming to straighten out. Especially when dealing with 700+ jobs a season. When money is proven to be owed and the insurance company releases more money because of the RT proof, we need to keep track of this so at the end of the season we can say "because of Roof Tracker, you saved $X in revenue that otherwise would've been lost, therefore Roof Tracker is worth $X to you".

**Comment by mitchbaum** [comment]
@RDoliveros @baumer67
Any thoughts or ideas on a way of implementing this feature? Maybe a button or point at time during the project lifecycle when you know for sure there is missing money?

My first thought:
Something like adding a button for the VA or sales rep to press when there is missing money and the insurance company claims they've sent it all which would flag the file as needing assistance in collecting the missing funds identified under the label "Insurance Still Owes Homeowner" on the summary page? That amount would be added to a global company counter along with the fileId and specific amount from the file so that at the end of the season we can print out a report list of which files money was saved on and the total amount...

**Comment by baumer67** [comment]
I have to think on that. Right now, the Salesrep triggers pursuit of missing money by emailing, Keith, Jake, Lucas, Info, with screenshots of the summary screen from the iOS app. Then OA pursues it. When the check is picked up containing the missing, money or portion of it Then the roof tracker is updated by the sales rep.

**Comment by mitchbaum** [comment]
Maybe it could be a checkbox that is switched with label "In pursuit of missing money" which will flag the file with a red color to indicate missing money is being pursued. Once the checkbox is switched to true it will alert the user asking if the ins still owes HO amount is the correct amount of money that is being pursued. If so, that amount will be added to the company count total. That would give a verification check so were not accidentally adding to the company count just by checking the box.

**Comment by baumer67** [comment]
Yes I like that.

**Comment by mitchbaum** [comment]
- [ ] iOS
- [ ] web

**Comment by mitchbaum** [comment]
- [ ] Redesign UI for Web

**Comment by mitchbaum** [comment]
- [ ] Add hidden 5 click feature to allow user to enter custom missing funds amount.

**Comment by mitchbaum** [comment]
- [ ] Verify feature works for independent user without company

**Comment by mitchbaum** [comment]
- [ ] fix NaN label error when user doesnt have any missing funds added yet on User Details flag UI

**Comment by mitchbaum** [comment]
Add table page with log of files that had missing funds found so user can see them and delete errors. Upon deletion, that total will be removed from user total and company total. 
Put this log as a button in setting. 
- [ ] iOS
- [ ] Web

**Comment by mitchbaum** [comment]
- [ ] Missing funds must be positive number, otherwise no missing funds are found
    - [ ] iOS
    - [ ] Web
