### ISSUE TITLE
Invoice total issue

### ISSUE THREAD

**Issue by baumer67** [mitchbaum/RoofTracker-Web-App#34]
I like the credit feature and summary display.  
Look at Michael Bennett the invoice balance doesn't calculate correctly.  I'm thinking we should have only COC entry in edit file and summary keeps as is. Thoughts?

**Comment by mitchbaum** [comment]
@baumer67 

Also what do you mean by "have only COC entry in edit file and summary keeps as is." do you mean remove the COC Total label from summary page or remove the ability to enter a COC from Add File but keep it on Edit File? Some pictures would be helpful...

**Comment by mitchbaum** [comment]
- [ ] Remove Invoice Total as an entry field in Create/Edit File page
- [ ] automatically generate invoice total based on COC field
- [ ] Fix Remaining Invoice - What's Due 
     - [ ] Subtract sum of credit from this total
